In [5]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import scipy.stats

In [6]:
# List 5 daily actions you perform on apps like Instagram, Zomato, or Flipkart, and for each, identify 
# whether the data generated is numerical or categorical.

data = {
    "App": ["Instagram", "Instagram", "Zomato", "Zomato", "Flipkart"],
    "Daily_Action": [
        "Like a post",
        "Watch reels",
        "Give restaurant rating",
        "Choose food category",
        "Purchase product"
    ],
    "Data_Generated": [
        "Yes",
        25,
        4.5,
        "Pizza",
        "Electronics"
    ],
    "Data_Type": [
        "Categorical",
        "Numerical",
        "Numerical",
        "Categorical",
        "Categorical"
    ]
}


df = pd.DataFrame(data)
df

         App            Daily_Action Data_Generated    Data_Type
0  Instagram             Like a post            Yes  Categorical
1  Instagram             Watch reels             25    Numerical
2     Zomato  Give restaurant rating            4.5    Numerical
3     Zomato    Choose food category          Pizza  Categorical
4   Flipkart        Purchase product    Electronics  Categorical

In [7]:
# Given this sample data from a music app: 
# ['Pop', 'Rock', 'Jazz', 'Hip-Hop', 'Pop', 'Rock', 'Jazz', 'Pop'], classify the type of data and explain your reasoning in 2-3 lines.

music_genera = pd.DataFrame({'music_genera':['Pop', 'Rock', 'Jazz', 'Hip-Hop', 'Pop', 'Rock', 'Jazz', 'Pop']})
music_genera

  music_genera
0          Pop
1         Rock
2         Jazz
3      Hip-Hop
4          Pop
5         Rock
6         Jazz
7          Pop

In [10]:
# 4.Suppose you are building a new playlist recommendation feature for
#  a Spotify-like app. List 3 basic statistical terms 
# (such as mean, median, mode, variance, etc.) that would be useful in analyzing user listening data, and explain each with a one-line example.


 

Playlist_likes = [100,9000,5000,2000,4000,300,200,5000,3000,5000]

df = pd.DataFrame({'playlist_likes':Playlist_likes})

df

   playlist_likes
0             100
1            9000
2            5000
3            2000
4            4000
5             300
6             200
7            5000
8            3000
9            5000

In [18]:
#mean 

print(f"playlist mean := {df['playlist_likes'].mean()}")

#median 

print(f"playlist median := {df['playlist_likes'].median()}")


# mode

print(f"playlist mode := {df['playlist_likes'].mode()}")

#variance

print(f"playlist variance := {df['playlist_likes'].var()}")

playlist mean := 3360.0
playlist median := 3500.0
playlist mode := 0    5000
Name: playlist_likes, dtype: int64
playlist variance := 8027111.111111111